### ISSUE TITLE
Code generation fails with an enum

### ISSUE THREAD

**Issue by faragos** [rtk-incubator/rtk-query-codegen#37]
When I try to generate an APi with an enum in it it fails. Example enum in a OpenAPI.json:

```
...
    "ExStatus": {
        "enum": [
          0,
          1,
          2
        ],
        "type": "integer",
        "format": "int32"
      },
...
```

My call:

> npx @rtk-incubator/rtk-query-codegen-openapi --file ./src/gen/TimeTrack.api.generated.ts --hooks ./api/TimeTrackAPI.json "--baseUrl" "https://localhost:5001"

The error:

```
TypeError: s.replace is not a function
    at escapeString (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:17131:18)
    at escapeNonAsciiString (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:17136:13)
    at Object.getLiteralText (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:14091:34)
    at getLiteralTextOfNode (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:104601:23)
    at emitLiteral (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:102107:24)
    at pipelineEmitWithHint (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:101919:32)
    at pipelineEmitWithComments (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:105009:17)
    at pipelineEmit (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:101547:13)
    at emitExpression (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:101532:20)
    at emitLiteralType (C:\Users\men\AppData\Roaming\npm-cache\_npx\2104\node_modules\@rtk-incubator\rtk-query-codegen-openapi\node_modules\typescript\lib\typescript.js:102505:13)
```

**Comment by msutkowski** [comment]
@faragos Can you please provide a copy of `TimeTrackAPI.json`?

**Comment by faragos** [comment]
I put the JSON into a .txt because GitHub doesn't support .json files.


[TimeTrackAPI.txt](https://github.com/rtk-incubator/rtk-query-codegen/files/6276799/TimeTrackAPI.txt)

**Comment by guvenkaranfil** [comment]
Is there any update on issue? I'm getting the same error, here's the json file I'm trying to generate on https://yawa-pick-test.azurewebsites.net/swagger/v1/swagger.json

**Comment by phryneas** [comment]
I'm sorry, I'm just hopelessly swamped with other work :disappointed: 

I have plans on getting the open issues some attention and get this whole repo over into https://github.com/reduxjs/redux-toolkit, but at the moment it seems like there are always coming things in between :confused:

**Comment by guvenkaranfil** [comment]
Thank you for quick response @phryneas . Could you please give me a how to debug this issue. Maybe I can send a fix about it. Is there any contribution or any guideline that i can follow

**Comment by phryneas** [comment]
The error message seems very strange to me as for me it reads like that error seems to appear during printing the code (I assume somewhere in the call stack it will finally end up in https://github.com/rtk-incubator/rtk-query-codegen/blob/next/src/generate.ts#L138, but the trace is cut off so I can't say for sure), which would mean that somewhere an AST node has gotten some *seriously* weird content.

I would honestly not really know where to start other than connecting the node debugger and breaking on exception, in the hopes of finding the exact AST node that's failing that way.

**Comment by phryneas** [comment]
@theZieger there is a `.vscode/launch.json` in this project, although I think the project has since seen some refactoring.
You theoretically should be able to open `src/bin/cli.ts`, set a breakpoint and then just do a "Run and Debug" -> "Current TS File".

**Comment by phryneas** [comment]
@ashnewport great analysis!
I think this should be fixed over in oazapfts - could you please file a PR over there and let me know when it is merged?

**Comment by theZieger** [comment]
@ashnewport thanks for the digging and explanation around debugging. Since I discovered the issue we changed our openapi to use strings instead of integers. 
Would also prefer seeing this fixed in the library instead having a workaround that must be removed later on again.

**Comment by ashnewport** [comment]
@phryneas and @theZieger this has been fixed in the oazapfts repo and the PR is now merged, https://github.com/cellular/oazapfts/pull/169

**Comment by phryneas** [comment]
> @phryneas and @theZieger this has been fixed in the oazapfts repo and the PR is now merged, [cellular/oazapfts#169](https://github.com/cellular/oazapfts/pull/169)

Great, I'll bump the dependency in the upcoming 1.0 beta

**Comment by phryneas** [comment]
The codegen is now published as `@rtk-query/codegen-openapi` and the code has moved over to [the Redux Toolkit monorepo](https://github.com/reduxjs/redux-toolkit/tree/master/packages/rtk-query-codegen-openapi).

As usage has changed as well, please [read the new documentation](https://redux-toolkit.js.org/rtk-query/usage/code-generation).


The new release references the new version of oazapfts, so this should be resolved.
